version: '3.6'
services:
  android-base:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-base

  android-instrumentation-tests:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-instrumentation-tests
    environment:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      INSTRUMENTATION_DEVICES:
      APP_LOCATION:

  android-linter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-linter
  
  android-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-builder
      args:
        - MAVEN_VERSION
    volumes:
      - ./build:/app/build
networks:
  default:
    name: ${BUILDKITE_JOB_ID:-android-maze-runner}