steps:
  - label: ':docker: Build Android apk builder image'
    plugins:
      - docker-compose#v2.6.0:
          build: android-builder
          cache-from:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
      - docker-compose#v2.6.0:
          push:
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-${BRANCH_NAME}
            - android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-latest
    env:
      MAVEN_VERSION: "3.6.1"

  - label: ':docker: Build Android maze runner image'
    plugins:
      - docker-compose#v2.6.0:
          build: android-maze-runner

  - wait

  - label: ':android: Build fixture APK'
    artifact_paths: build/fixture.apk
    plugins:
      - docker-compose#v2.6.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"

  - wait

  - label: ':android: Android 5 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_5"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 6 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_6"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 7 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_7"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 8 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_8"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: ':android: Android 9 end-to-end tests'
    plugins:
      artifacts#v1.2.0:
        download: "build/fixture.apk"
      docker-compose#v2.6.0:
        run: android-maze-runner
    env:
      DEVICE_TYPE: "ANDROID_9"
      APP_LOCATION: "/app/build/fixture.apk"
    concurrency: 5
    concurrency_group: 'browserstack-app'
